/* DO NOT EDIT THIS FILE - it is machine generated */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "com_cj_mqtt_HKPacket.h"
#include "crypt_aes.h"

/*
 * Class:     com_cj_mqtt_HKPacket
 * Method:    aesDecode
 * Signature: ([BLjava/lang/String;Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_cj_mqtt_HKPacket_aesDecode(JNIEnv *env, jclass cls,
		jbyteArray jdata, jstring jkey, jstring jiv) {
	unsigned char key[16], iv[16];
	const char *tmp;
	int delen = 0;
	unsigned char *decodes = NULL;

	tmp = (*env)->GetStringUTFChars(env, jkey, JNI_FALSE);
	strncpy(key, tmp, 16);
	(*env)->ReleaseStringUTFChars(env, jkey, tmp);

	tmp = (*env)->GetStringUTFChars(env, jiv, JNI_FALSE);
	strncpy(iv, tmp, 16);
	(*env)->ReleaseStringUTFChars(env, jiv, tmp);

	jbyte *in = NULL;
	int inlen = (*env)->GetArrayLength(env, jdata);

	in = (*env)->GetByteArrayElements(env, jdata, JNI_FALSE); //jbyteArray转为jbyte*

	hk_aes_decode(in, inlen, &decodes, &delen, key, iv, 1);

	(*env)->ReleaseByteArrayElements(env, jdata, in, 0);  //释放掉

	if (decodes == NULL) {
		return NULL;
	}

	jbyteArray jarrRV = (*env)->NewByteArray(env, delen);
	(*env)->SetByteArrayRegion(env, jarrRV, 0, delen, decodes);
	free(decodes);
	return jarrRV;
}

/*
 * Class:     com_cj_mqtt_HKPacket
 * Method:    aesEncode
 * Signature: ([BLjava/lang/String;Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_cj_mqtt_HKPacket_aesEncode(JNIEnv *env, jclass cls,
		jbyteArray jdata, jstring jkey, jstring jiv) {
	unsigned char key[16], iv[16];
	const char *tmp;
	int enlen = 0;
	unsigned char *encodes = NULL;

	tmp = (*env)->GetStringUTFChars(env, jkey, JNI_FALSE);
	strncpy(key, tmp, 16);
	(*env)->ReleaseStringUTFChars(env, jkey, tmp);

	tmp = (*env)->GetStringUTFChars(env, jiv, JNI_FALSE);
	strncpy(iv, tmp, 16);
	(*env)->ReleaseStringUTFChars(env, jiv, tmp);

	jbyte *in = NULL;
	int inlen = (*env)->GetArrayLength(env, jdata);

	in = (*env)->GetByteArrayElements(env, jdata, JNI_FALSE); //jbyteArray转为jbyte*

	hk_aes_encode(in, inlen, &encodes, &enlen, key, iv);

	(*env)->ReleaseByteArrayElements(env, jdata, in, 0);  //释放掉

	if (encodes == NULL) {
		return NULL;
	}

	jbyteArray jarrRV = (*env)->NewByteArray(env, enlen);
	(*env)->SetByteArrayRegion(env, jarrRV, 0, enlen, encodes);
	free(encodes);
	return jarrRV;
}

