/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cj_mqtt_HKPacket */

#ifndef _Included_com_cj_mqtt_HKPacket
#define _Included_com_cj_mqtt_HKPacket
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cj_mqtt_HKPacket
 * Method:    aesDecode
 * Signature: ([BLjava/lang/String;Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_cj_mqtt_HKPacket_aesDecode
  (JNIEnv *, jclass, jbyteArray, jstring, jstring);

/*
 * Class:     com_cj_mqtt_HKPacket
 * Method:    aesEncode
 * Signature: ([BLjava/lang/String;Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_cj_mqtt_HKPacket_aesEncode
  (JNIEnv *, jclass, jbyteArray, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
